//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public System.Guid id { get; set; }
        public string recordNumber { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string createdBy { get; set; }
        public Nullable<bool> isVaccine { get; set; }
        public string notes { get; set; }
        public System.Guid petId { get; set; }
        public Nullable<System.Guid> vaccineId { get; set; }
        public string status { get; set; }
        public string tags { get; set; }
        public string type { get; set; }
    
        public virtual Pet Pet { get; set; }
        public virtual Vaccine Vaccine { get; set; }
    }
}
